# -*- coding: utf-8 -*-
"""Image_Classification_MobileNet_Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uStJqoDbn8SuwrBoEfd-7YGhsOV3_UyZ

# Image Classification using Transfer Learning (MobileNetV2)

This notebook trains an image classification model on the CIFAR-10 dataset using **MobileNetV2**.

- Dataset: CIFAR-10 (auto-download)
- Framework: TensorFlow / Keras
- Platform: Google Colab
"""

!pip install tensorflow

import tensorflow as tf
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D
from tensorflow.keras.models import Model
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.datasets import cifar10


print('TensorFlow version:', tf.__version__)

(x_train, y_train), (x_val, y_val) = cifar10.load_data()

x_train = x_train / 255.0
x_val = x_val / 255.0

y_train = to_categorical(y_train, 10)
y_val = to_categorical(y_val, 10)

x_train = tf.image.resize(x_train, (96, 96))
x_val = tf.image.resize(x_val, (96, 96))

print(x_train.shape, y_train.shape)

base_model = MobileNetV2(weights='imagenet', include_top=False, input_shape=(96,96,3))
base_model.trainable = False

x = GlobalAveragePooling2D()(base_model.output)
output = Dense(10, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=output)

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

model.fit(
    x_train, y_train,
    validation_data=(x_val, y_val),
    epochs=5,
    batch_size=32
)

model.save('mobilenet_cifar10.h5')
print('✅ Model saved successfully')